name: gossip
description: ""

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  get_it: ^9.2.0
  firebase_database: ^12.1.1
  firebase_auth: ^6.1.3
  google_fonts: ^6.3.3
  firebase_core: ^4.3.0
  image_picker: ^1.2.1
  go_router: ^17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true